image: "registry.gitlab.e.foundation/e/os/docker-android-apps-cicd:latest"

stages:
- build

before_script:
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

build:
  stage: build
  script:
  - ./gradlew build -x test
  artifacts:
    paths:
    - app/build/outputs/apk
